config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end
  # アカウント登録後の遷移先
  def after_sign_up_path_for(resource)
    user_path(resource.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!#ログイン中のユーザーのみ

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @user_book = Book.find(params[:id])
    @user = @user_book.user
    @book = Book.new
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
     @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
     @book = Book.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_book
    #   @book = Book.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!#ログイン中のユーザーのみ
  def index
    @users = User.all
    @book = Book.new
    @user =  current_user
  end

  def show
    @user = User.find(params[:id])
    @user_book = @user.books
    @book = Book.new #空のインスタンス生成
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id]) 
    @user.update(user_params)
    redirect_to user_path()
  end

  def user_params
    params.require(:user).permit(:name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'layouts/profile', user: @user %>



<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book_path(book) do %>
              <%= book.title %>
            <% end %>
        </td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'layouts/profile', user: @user %>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

      <tr>
        <td><%= @user_book.title %></td>
        <td><%= @user_book.body %></td>
        <% if @user.id == current_user.id %>
        <td><%= link_to 'Edit', edit_book_path(@user_book) %></td>
        <td><%= link_to 'Destroy', @user_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>

  </tbody>
</table>

app/views/homes/about.html.erb
<div class="container">
  <p id="notice"></p>
  <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
</div>

app/views/homes/top.html.erb
<div class="body">
  <div class="container">
    <%= render 'layouts/notifications' %>
    <div class="row">
      <div class="top-message col-md-offset-3 col-md-6">
        <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
            <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
            <p>you can share and exchange  your opinions , impressions , and emotions</p>
            <p> about various books!</p>
        <div class="btn-wrapper">
          <div class="row">
            <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
          </div>
          <div class="row">
            <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, class: "flash flash__#{key}" ) %>
<% end %>

app/views/layouts/_profile.html.erb
<div class="col-xs-3">
  <h2>User info</h2>
    <!--<p><= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></p>-->
     <table class="table">
     <tbody>
      <tr></tr>
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
    </tbody>
    </table>
  <div class="row">
   <% if user.id ==  current_user.id %>
      <%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    <% else %>
    <!--ログインしたユーザの詳細に戻る-->
      <%= link_to "", user_path(current_user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    <% end %>
  </div>
    <h2>New book</h2>
    <%= render 'books/form', book: @book %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="">
               <%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
              </li>
              <li class="">
                <%= link_to 'Users', users_path, class: "glyphicon glyphicon-user users" %>
              </li>
              <li class="">
                <%= link_to 'Books', books_path, class: "glyphicon glyphicon-book books" %>
              </li>
              <li class="">
                <%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %>
              </li>
            <% else %>
              <li class="">
                <%= link_to "Home", root_path, class: "glyphicon glyphicon-home home" %>
              </li>
              <li class="">
                <%= link_to "About", home_about_path, class: "glyphicon glyphicon-link about" %>
              </li>
              <li class="">
                <%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %>
              </li>
              <li class="">
                <%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container">
      	<div class="row">
        	<div class="col-xs-3 col-xs-offset-9">
        		<p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model:@user, local:true do |f| %>
<%= f.label:name %><br/>
<%= f.text_field:name %>

<%= f.label:introduction %><br/>
<%= f.text_field:introduction %>

<div><%= f.submit '編集' %></div>
<% end %>

<!--<= link_to 'Show', @book %> |-->
<%= link_to 'Back', books_path %>

app/views/users/index.html.erb
<div class="container">
<div class="row">
<%= render 'layouts/profile', user: @user %>

  <div class="col-xs-9">
    <h2>Books</h2>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @users.each do |user| %>
      <tr>
        <td></td>
        <td><%= user.name %></td>
        <td><%= link_to 'show', user_path(user) %></td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
<%= render 'layouts/profile', user: @user %>
  <div class="col-xs-9">
    <h2>Books</h2>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @user_book.each do |book| %>
      <tr>
        <td></td>
        <td>
          <%= link_to book_path(book) do %>
            <%= book.title %>
          <% end %>
          </td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>
</div>
</div>